name:                msc-financial-computing
version:             0.1.0.0
github:              "githubuser/msc-financial-computing"
license:             BSD3
author:              "Benedict Aas"
maintainer:          "x@shou.io"
copyright:           "2018 Benedict Aas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Shou/msc-financial-computing#readme>

dependencies:
- base >= 4.7 && < 5
- random == 1.1
- mwc-random == 0.13.6.0
- vector == 0.12.0.1
- vector-sized == 1.1.1.0
- bed-and-breakfast == 0.5
- matrix-static == 0.2
- gnuplot == 0.5.5.3

library:
  source-dirs: src
  msc-financial-computing:
    default-extensions:
      - MultiParamTypeClasses
      - TypeOperators
      - TypeApplications
      - TypeFamilies
      - BangPatterns
      - GADTs
      - ScopedTypeVariables
      - PolyKinds
      - StarIsType
      - TupleSections
      - PartialTypeSignatures
      - TypeInType
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

